"""Application services: the queue, logging, swaps, the impact rule, benchmarks.

This is the layer that turns durable rows into the pure engine's inputs and
writes its outputs back. Everything that decides *policy* lives in `engine`;
everything that decides *what happened* lives here.
"""

from __future__ import annotations

import json
import sqlite3
import uuid
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from typing import Any

from . import db
from .engine import (
    BenchmarkCycle,
    PauseWindow,
    PriorOutcome,
    SessionRecord,
    WeekContext,
    WeekOutcome,
    evaluate_week,
    phase_exit_status,
    training_rate,
)
from .plan import Plan, PlanSession, load_plan
from .timeutil import iso_week, now, today, week_end, week_start

LOWER_LIMB = {"ankle", "knee", "shin"}
PAIN_LOCATIONS = ["ankle", "knee", "shin", "hip", "back", "shoulder", "other"]
IMPACT_PAIN_THRESHOLD = 3
IMPACT_WINDOW_DAYS = 14
PAIN_STOP_THRESHOLD = 5
VOLUNTARY_SWAPS_PER_WEEK = 1


class ServiceError(Exception):
    """A rejected action, with a message safe to show the athlete."""


@dataclass(frozen=True)
class UpNext:
    session: PlanSession
    substituted_for: PlanSession | None = None
    reason: str | None = None

    @property
    def is_substitution(self) -> bool:
        return self.substituted_for is not None


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# --------------------------------------------------------------------------
# Queue
# --------------------------------------------------------------------------


def current_session(conn: sqlite3.Connection, plan: Plan | None = None) -> UpNext | None:
    """The session at the pointer, with the impact rule already applied.

    The automatic substitution is resolved at read time rather than written into
    the queue, so it disappears on its own once the pain stops being reported.
    """
    plan = plan or load_plan()
    progress = db.fetch_progress(conn)
    pointer = progress["pointer_slug"]
    if pointer is None:
        return None

    session = plan.session(pointer)
    if session is None:
        return None

    if session.counts_as == "run_exposure" and impact_substitution_active(conn):
        for alt in session.alternatives:
            if alt.reason == "impact":
                replacement = plan.session(alt.slug)
                if replacement is not None:
                    return UpNext(replacement, substituted_for=session, reason="impact")

    return UpNext(session)


def upcoming(conn: sqlite3.Connection, count: int = 7, plan: Plan | None = None) -> list[PlanSession]:
    plan = plan or load_plan()
    progress = db.fetch_progress(conn)
    return list(plan.after(progress["pointer_slug"])[:count])


def _advance_pointer(conn: sqlite3.Connection, plan: Plan, from_slug: str) -> None:
    session = plan.session(from_slug)
    if session is None:
        return
    following = plan.sessions[session.ordinal + 1 :]
    conn.execute(
        "UPDATE progress SET pointer_slug = ? WHERE id = 1",
        (following[0].slug if following else None,),
    )


# --------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------


def log_session(
    conn: sqlite3.Connection,
    *,
    slug: str,
    actor: str,
    training_date: date | None = None,
    variant: str | None = None,
    duration_min: int | None = None,
    rpe: int | None = None,
    pain_score: int | None = None,
    pain_location: str | None = None,
    note: str | None = None,
    substituted_from: str | None = None,
    substitution_reason: str | None = None,
    idempotency_key: str | None = None,
    plan: Plan | None = None,
) -> int:
    """Record a completed session and advance the queue.

    `idempotency_key` is generated by the client so an offline completion
    replayed after reconnect cannot double-log. A duplicate key is not an error:
    it returns the original event, which is what makes replay safe.
    """
    plan = plan or load_plan()
    session = plan.session(slug)
    if session is None:
        raise ServiceError(f"unknown session {slug}")

    key = idempotency_key or str(uuid.uuid4())
    existing = conn.execute(
        "SELECT id FROM session_events WHERE idempotency_key = ?", (key,)
    ).fetchone()
    if existing is not None:
        return int(existing["id"])

    stop = active_pain_stop(conn)
    if stop is not None and stop["counts_as"] == session.counts_as:
        raise ServiceError(
            "Training of this kind is paused until your coach reviews the pain you logged."
        )

    if pain_location is not None and pain_location not in PAIN_LOCATIONS:
        raise ServiceError(f"unknown pain location {pain_location!r}")

    advance_from = substituted_from or slug
    day = training_date or today()

    cursor = conn.execute(
        """
        INSERT INTO session_events (
            slug, revision, kind, training_date, completed_at, variant,
            substituted_from, substitution_reason, duration_min, rpe,
            pain_score, pain_location, note, idempotency_key, snapshot_json,
            actor, created_at
        ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """,
        (
            slug,
            plan.version,
            "swapped" if substituted_from else "completed",
            day.isoformat(),
            _utc_now(),
            variant or session.variant,
            substituted_from,
            substitution_reason,
            duration_min if duration_min is not None else session.cap_minutes,
            rpe,
            pain_score,
            pain_location,
            note,
            key,
            json.dumps(
                {
                    "title": session.title,
                    "kind": session.kind,
                    "counts_as": session.counts_as,
                    "detail": [dict(d) for d in session.detail],
                }
            ),
            actor,
            _utc_now(),
        ),
    )
    _advance_pointer(conn, plan, advance_from)
    return int(cursor.lastrowid)


def skip_session(
    conn: sqlite3.Connection, *, slug: str, actor: str, reason: str, plan: Plan | None = None
) -> int:
    """Record an explicit "not today".

    Deliberately does **not** advance the pointer: nothing is lost, the queue
    simply waits. Its value is that an intentional skip is distinguishable from
    silence, both for the coach and for the reminder logic.
    """
    plan = plan or load_plan()
    session = plan.session(slug)
    if session is None:
        raise ServiceError(f"unknown session {slug}")

    cursor = conn.execute(
        """
        INSERT INTO session_events (
            slug, revision, kind, training_date, completed_at, skip_reason,
            idempotency_key, snapshot_json, actor, created_at
        ) VALUES (?,?,?,?,?,?,?,?,?,?)
        """,
        (
            slug,
            plan.version,
            "skipped",
            today().isoformat(),
            _utc_now(),
            reason,
            str(uuid.uuid4()),
            json.dumps({"title": session.title, "kind": session.kind}),
            actor,
            _utc_now(),
        ),
    )
    return int(cursor.lastrowid)


def void_event(conn: sqlite3.Connection, *, event_id: int, actor: str, plan: Plan | None = None) -> None:
    """Reverse a mis-tap. Append-only: the row stays, marked voided."""
    plan = plan or load_plan()
    row = conn.execute(
        "SELECT * FROM session_events WHERE id = ? AND voided_at IS NULL", (event_id,)
    ).fetchone()
    if row is None:
        raise ServiceError("event not found or already voided")

    conn.execute(
        "UPDATE session_events SET voided_at = ?, voided_by = ? WHERE id = ?",
        (_utc_now(), actor, event_id),
    )

    if row["kind"] in ("completed", "swapped"):
        # Rewind the pointer to whatever this event advanced past.
        rewind_to = row["substituted_from"] or row["slug"]
        session = plan.session(rewind_to)
        progress = db.fetch_progress(conn)
        pointer = progress["pointer_slug"]
        current = plan.session(pointer) if pointer else None
        if session is not None and (current is None or session.ordinal < current.ordinal):
            conn.execute(
                "UPDATE progress SET pointer_slug = ? WHERE id = 1", (session.slug,)
            )


# --------------------------------------------------------------------------
# Swaps
# --------------------------------------------------------------------------


def swap_allowance_used(conn: sqlite3.Connection, reference: date | None = None) -> int:
    day = reference or today()
    label = iso_week(day)
    rows = conn.execute(
        """
        SELECT training_date FROM session_events
        WHERE voided_at IS NULL AND substitution_reason = 'voluntary'
        """
    ).fetchall()
    return sum(1 for r in rows if iso_week(date.fromisoformat(r["training_date"])) == label)


def resolve_swap(
    conn: sqlite3.Connection, *, slug: str, alternative_slug: str, plan: Plan | None = None
) -> PlanSession:
    """Validate a voluntary swap and return the session to be performed.

    Alternatives are authored on the template, never chosen from the queue, so
    there is nothing to defer: he cannot pull an easy session forward from month
    12 and push the hard one back indefinitely.
    """
    plan = plan or load_plan()
    session = plan.session(slug)
    if session is None:
        raise ServiceError(f"unknown session {slug}")

    allowed = {alt.slug for alt in session.alternatives}
    if alternative_slug not in allowed:
        raise ServiceError("That is not a declared alternative for this session.")

    if swap_allowance_used(conn) >= VOLUNTARY_SWAPS_PER_WEEK:
        raise ServiceError("You have already used this week's swap.")

    replacement = plan.session(alternative_slug)
    if replacement is None:
        raise ServiceError(f"unknown alternative {alternative_slug}")
    return replacement


# --------------------------------------------------------------------------
# Impact rule
# --------------------------------------------------------------------------


def impact_substitution_active(conn: sqlite3.Connection, reference: date | None = None) -> bool:
    """Two run exposures inside 14 days, same lower-limb location, pain >= 3.

    v1 said "two consecutive logs", which Codex correctly called unsafe -- those
    could be two unrelated sessions weeks apart. Recency and exposure both matter.
    """
    day = reference or today()
    cutoff = day - timedelta(days=IMPACT_WINDOW_DAYS)
    rows = conn.execute(
        """
        SELECT training_date, pain_score, pain_location, snapshot_json
        FROM session_events
        WHERE voided_at IS NULL
          AND kind IN ('completed', 'swapped')
          AND pain_score IS NOT NULL
          AND pain_location IS NOT NULL
        ORDER BY training_date DESC, id DESC
        """
    ).fetchall()

    by_location: dict[str, int] = {}
    for row in rows:
        training_day = date.fromisoformat(row["training_date"])
        if training_day < cutoff or training_day > day:
            continue
        snapshot = json.loads(row["snapshot_json"])
        if snapshot.get("counts_as") != "run_exposure":
            continue
        location = row["pain_location"]
        if location not in LOWER_LIMB or row["pain_score"] < IMPACT_PAIN_THRESHOLD:
            continue
        by_location[location] = by_location.get(location, 0) + 1
        if by_location[location] >= 2:
            return True
    return False


def active_pain_stop(conn: sqlite3.Connection) -> dict[str, Any] | None:
    """An unacknowledged pain report of 5 or more halts that kind of training.

    Holding progression is not enough. An app should not quietly keep
    programming through reported pain, so this blocks logging of the same kind
    until the coach acknowledges it.
    """
    row = conn.execute(
        """
        SELECT e.id, e.pain_score, e.pain_location, e.training_date, e.snapshot_json
        FROM session_events e
        LEFT JOIN acknowledgements a
               ON a.event_id = e.id AND a.kind = 'pain_stop'
        WHERE e.voided_at IS NULL
          AND e.pain_score >= ?
          AND a.id IS NULL
        ORDER BY e.training_date DESC, e.id DESC
        LIMIT 1
        """,
        (PAIN_STOP_THRESHOLD,),
    ).fetchone()
    if row is None:
        return None
    snapshot = json.loads(row["snapshot_json"])
    return {
        "event_id": row["id"],
        "pain_score": row["pain_score"],
        "pain_location": row["pain_location"],
        "training_date": row["training_date"],
        "counts_as": snapshot.get("counts_as"),
    }


def acknowledge_pain_stop(
    conn: sqlite3.Connection, *, event_id: int, actor: str, note: str | None = None
) -> None:
    conn.execute(
        """
        INSERT INTO acknowledgements (kind, event_id, actor, note, created_at)
        VALUES ('pain_stop', ?, ?, ?, ?)
        """,
        (event_id, actor, note, _utc_now()),
    )


# --------------------------------------------------------------------------
# Pauses
# --------------------------------------------------------------------------


def start_pause(
    conn: sqlite3.Connection, *, kind: str, start: date, end: date | None, note: str | None = None
) -> int:
    cursor = conn.execute(
        "INSERT INTO pause_windows (kind, start_date, end_date, note, created_at) VALUES (?,?,?,?,?)",
        (kind, start.isoformat(), end.isoformat() if end else None, note, _utc_now()),
    )
    return int(cursor.lastrowid)


def end_pause(conn: sqlite3.Connection, *, pause_id: int, end: date | None = None) -> None:
    conn.execute(
        "UPDATE pause_windows SET end_date = ? WHERE id = ?",
        ((end or today()).isoformat(), pause_id),
    )


def load_pauses(conn: sqlite3.Connection) -> tuple[PauseWindow, ...]:
    return tuple(
        PauseWindow(
            kind=row["kind"],
            start_date=date.fromisoformat(row["start_date"]),
            end_date=date.fromisoformat(row["end_date"]) if row["end_date"] else None,
        )
        for row in conn.execute("SELECT * FROM pause_windows ORDER BY start_date")
    )


# --------------------------------------------------------------------------
# Benchmarks
# --------------------------------------------------------------------------


def cycle_for_week(global_week: int) -> int:
    return max(1, (global_week + 3) // 4)


def record_benchmark(
    conn: sqlite3.Connection,
    *,
    cycle: int,
    test_key: str,
    value: float,
    extra: dict[str, Any] | None = None,
    reference: date | None = None,
) -> None:
    conn.execute(
        """
        INSERT INTO benchmarks (cycle, iso_week, test_key, value, extra_json, recorded_at)
        VALUES (?,?,?,?,?,?)
        ON CONFLICT (cycle, test_key) DO UPDATE SET
            value = excluded.value,
            extra_json = excluded.extra_json,
            recorded_at = excluded.recorded_at
        """,
        (
            cycle,
            iso_week(reference or today()),
            test_key,
            float(value),
            json.dumps(extra or {}),
            _utc_now(),
        ),
    )


def load_benchmark_cycles(conn: sqlite3.Connection) -> tuple[BenchmarkCycle, ...]:
    cycles: dict[int, dict[str, float]] = {}
    for row in conn.execute("SELECT cycle, test_key, value FROM benchmarks ORDER BY cycle"):
        cycles.setdefault(row["cycle"], {})[row["test_key"]] = row["value"]
    return tuple(BenchmarkCycle(cycle=c, values=v) for c, v in sorted(cycles.items()))


# --------------------------------------------------------------------------
# Weekly evaluation
# --------------------------------------------------------------------------


def _records(conn: sqlite3.Connection, plan: Plan) -> list[SessionRecord]:
    records = []
    for row in db.live_events(conn):
        snapshot = json.loads(row["snapshot_json"])
        counts_as = snapshot.get("counts_as")
        if counts_as is None:
            session = plan.session(row["slug"])
            counts_as = session.counts_as if session else "unknown"
        records.append(
            SessionRecord(
                slug=row["slug"],
                kind=row["kind"],
                training_date=date.fromisoformat(row["training_date"]),
                counts_as=counts_as,
                pain_score=row["pain_score"],
                pain_location=row["pain_location"],
            )
        )
    return records


def _prior_outcomes(conn: sqlite3.Connection, before: str) -> tuple[PriorOutcome, ...]:
    rows = conn.execute(
        "SELECT * FROM week_outcomes WHERE iso_week < ? ORDER BY iso_week", (before,)
    ).fetchall()
    return tuple(
        PriorOutcome(
            iso_week=r["iso_week"],
            floor_met=bool(r["floor_met"]),
            sessions_counted=r["sessions_counted"],
            status=r["status"],
        )
        for r in rows
    )


def build_context(
    conn: sqlite3.Connection, monday: date, plan: Plan | None = None
) -> WeekContext:
    plan = plan or load_plan()
    progress = db.fetch_progress(conn)
    label = iso_week(monday)
    start, end = week_start(monday), week_end(monday)

    records = _records(conn, plan)
    events = tuple(r for r in records if start <= r.training_date <= end)
    history = tuple(r for r in records if r.training_date < start)

    pointer = progress["pointer_slug"]
    remaining = len(plan.after(pointer)) if pointer else 0

    last = conn.execute(
        "SELECT * FROM week_outcomes WHERE iso_week < ? ORDER BY iso_week DESC LIMIT 1", (label,)
    ).fetchone()
    previous_projection = date.fromisoformat(
        last["projected_race_date"] if last else progress["projected_race_date"]
    )
    buffer_weeks = last["buffer_after"] if last else progress["buffer_weeks"]

    return WeekContext(
        iso_week=label,
        week_start=start,
        week_end=end,
        phase=plan.phase(progress["phase"]),
        events=events,
        history=history,
        prior_outcomes=_prior_outcomes(conn, label),
        pauses=load_pauses(conn),
        benchmarks=load_benchmark_cycles(conn),
        buffer_weeks=float(buffer_weeks),
        sessions_remaining=remaining,
        baseline_race_date=date.fromisoformat(progress["baseline_race_date"]),
        previous_projection=previous_projection,
        evaluated_on=today(),
    )


def persist_outcome(conn: sqlite3.Connection, outcome: WeekOutcome) -> None:
    """Write once. Outcomes are never recomputed from mutable logs."""
    conn.execute(
        """
        INSERT INTO week_outcomes (
            iso_week, floor_required, sessions_counted, floor_met, status,
            buffer_delta, buffer_after, projected_race_date, detail_json, evaluated_at
        ) VALUES (?,?,?,?,?,?,?,?,?,?)
        ON CONFLICT (iso_week) DO NOTHING
        """,
        (
            outcome.iso_week,
            outcome.floor_required,
            outcome.sessions_counted,
            int(outcome.floor_met),
            outcome.status,
            outcome.buffer_delta,
            outcome.buffer_after,
            outcome.projected_race_date.isoformat(),
            json.dumps(outcome.detail),
            _utc_now(),
        ),
    )
    conn.execute(
        "UPDATE progress SET buffer_weeks = ?, projected_race_date = ? WHERE id = 1",
        (outcome.buffer_after, outcome.projected_race_date.isoformat()),
    )


def evaluate_closed_weeks(
    conn: sqlite3.Connection, reference: date | None = None, plan: Plan | None = None
) -> list[WeekOutcome]:
    """Evaluate every complete week that has no outcome yet.

    Idempotent: running it twice on the same day changes nothing, which is what
    lets it be both a Monday job and a safety net on every request.
    """
    plan = plan or load_plan()
    progress = db.fetch_progress(conn)
    day = reference or today()

    monday = week_start(date.fromisoformat(progress["plan_start"]))
    current_monday = week_start(day)
    outcomes: list[WeekOutcome] = []

    while monday < current_monday:
        label = iso_week(monday)
        exists = conn.execute(
            "SELECT 1 FROM week_outcomes WHERE iso_week = ?", (label,)
        ).fetchone()
        if exists is None:
            outcome = evaluate_week(build_context(conn, monday, plan))
            persist_outcome(conn, outcome)
            outcomes.append(outcome)
        monday += timedelta(days=7)

    return outcomes


# --------------------------------------------------------------------------
# Phase progression
# --------------------------------------------------------------------------


def phase_manual_confirmed(conn: sqlite3.Connection, phase: int) -> bool:
    row = conn.execute(
        "SELECT 1 FROM acknowledgements WHERE kind = 'phase_manual' AND note = ?",
        (str(phase),),
    ).fetchone()
    return row is not None


def confirm_phase_manual(conn: sqlite3.Connection, *, phase: int, actor: str) -> None:
    conn.execute(
        "INSERT INTO acknowledgements (kind, actor, note, created_at) VALUES ('phase_manual',?,?,?)",
        (actor, str(phase), _utc_now()),
    )


def sessions_completed(conn: sqlite3.Connection) -> int:
    row = conn.execute(
        """
        SELECT COUNT(*) AS n FROM session_events
        WHERE voided_at IS NULL AND kind IN ('completed','swapped')
        """
    ).fetchone()
    return int(row["n"])


def phase_progress(conn: sqlite3.Connection, plan: Plan | None = None) -> dict[str, Any]:
    plan = plan or load_plan()
    progress = db.fetch_progress(conn)
    phase = plan.phase(progress["phase"])
    entry = date.fromisoformat(progress["phase_entry_date"])

    outcomes = tuple(
        PriorOutcome(
            iso_week=r["iso_week"],
            floor_met=bool(r["floor_met"]),
            sessions_counted=r["sessions_counted"],
            status=r["status"],
        )
        for r in conn.execute(
            "SELECT * FROM week_outcomes WHERE iso_week >= ? ORDER BY iso_week",
            (iso_week(entry),),
        )
    )

    complete, rows = phase_exit_status(
        plan,
        phase,
        outcomes,
        sessions_completed(conn),
        phase_manual_confirmed(conn, phase.number),
    )
    return {"phase": phase, "complete": complete, "criteria": rows}


def advance_phase_if_ready(conn: sqlite3.Connection, plan: Plan | None = None) -> bool:
    plan = plan or load_plan()
    status = phase_progress(conn, plan)
    if not status["complete"]:
        return False
    phase = status["phase"]
    following = [p for p in plan.phases if p.number > phase.number]
    if not following:
        return False
    conn.execute(
        "UPDATE progress SET phase = ?, phase_entry_date = ? WHERE id = 1",
        (following[0].number, today().isoformat()),
    )
    return True


# --------------------------------------------------------------------------
# Read models
# --------------------------------------------------------------------------


def week_strip(conn: sqlite3.Connection, reference: date | None = None) -> dict[str, Any]:
    """This week's checkbox row: one cell per day, plus floor progress."""
    day = reference or today()
    start = week_start(day)
    plan = load_plan()
    progress = db.fetch_progress(conn)
    phase = plan.phase(progress["phase"])

    rows = db.events_for_weeks(conn, [iso_week(day)])
    by_day: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        by_day.setdefault(row["training_date"], []).append(
            {
                "id": row["id"],
                "kind": row["kind"],
                "title": json.loads(row["snapshot_json"]).get("title"),
            }
        )

    days = []
    for offset in range(7):
        d = start + timedelta(days=offset)
        entries = by_day.get(d.isoformat(), [])
        days.append(
            {
                "date": d,
                "label": d.strftime("%a"),
                "is_today": d == day,
                "entries": entries,
                "done": any(e["kind"] in ("completed", "swapped") for e in entries),
                "skipped": any(e["kind"] == "skipped" for e in entries),
            }
        )

    counted = sum(1 for d in days if d["done"])
    return {
        "days": days,
        "counted": counted,
        "floor": phase.floor,
        "target": phase.target,
        "floor_met": counted >= phase.floor,
    }


def dashboard_state(conn: sqlite3.Connection, plan: Plan | None = None) -> dict[str, Any]:
    plan = plan or load_plan()
    progress = db.fetch_progress(conn)
    phase = plan.phase(progress["phase"])
    records = _records(conn, plan)

    rate = training_rate(tuple(records), today(), float(phase.target))
    pointer = progress["pointer_slug"]
    remaining = len(plan.after(pointer)) if pointer else 0

    return {
        "phase": phase,
        "buffer_weeks": progress["buffer_weeks"],
        "baseline_race_date": date.fromisoformat(progress["baseline_race_date"]),
        "projected_race_date": date.fromisoformat(progress["projected_race_date"]),
        "sessions_remaining": remaining,
        "sessions_completed": sessions_completed(conn),
        "rate": round(rate, 2),
        "pain_stop": active_pain_stop(conn),
        "impact_active": impact_substitution_active(conn),
        "swaps_used": swap_allowance_used(conn),
        "swaps_allowed": VOLUNTARY_SWAPS_PER_WEEK,
        "plan_complete": pointer is None,
    }


def benchmark_table(conn: sqlite3.Connection, plan: Plan | None = None) -> dict[str, Any]:
    """Latest cycle against the one before, per test, for the progress bars."""
    plan = plan or load_plan()
    progress = db.fetch_progress(conn)
    tests = plan.battery_for_phase(progress["phase"])
    cycles = load_benchmark_cycles(conn)

    latest = cycles[-1] if cycles else None
    previous = cycles[-2] if len(cycles) > 1 else None

    rows = []
    for test in tests:
        current = latest.values.get(test["key"]) if latest else None
        before = previous.values.get(test["key"]) if previous else None
        change = None
        if current is not None and before:
            change = (current - before) / before * 100
        rows.append(
            {
                "key": test["key"],
                "name": test["name"],
                "unit": test["unit"],
                "protocol": test["protocol"],
                "current": current,
                "previous": before,
                "change_pct": change,
            }
        )
    return {
        "tests": rows,
        "cycle": latest.cycle if latest else None,
        "tested": latest is not None,
    }
